// Build the typed rule surface into the actual legacy-compatible role engine.
// The marked payload is generated; surrounding commands remain authored adapters.
import {build} from '../samples/threejs-recovery/node_modules/esbuild/lib/main.js';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {writeChangedArtifact} from './artifact-io.mjs';
const target=new URL('../source/shared/engine.js',import.meta.url);
const result=await build({entryPoints:[fileURLToPath(new URL('../source/domain/runtime.ts',import.meta.url))],bundle:true,write:false,format:'iife',globalName:'SEADomain',minify:true,target:'es2022',legalComments:'inline'});
const payload='// BEGIN TYPED DOMAIN (generated by tools/build-domain.mjs)\n'+result.outputFiles[0].text.trimEnd()+'\n// END TYPED DOMAIN\n';
const original=readFileSync(target,'utf8').replace(/\r\n?/g,'\n');
const marker=/\/\/ BEGIN TYPED DOMAIN[^\n]*\n[\s\S]*?\/\/ END TYPED DOMAIN\n/;
const next=marker.test(original)?original.replace(marker,()=>payload):payload+original;
if(process.argv.includes('--check')){
 if(next!==original)throw Error('Typed domain payload differs; run node tools/build-domain.mjs');
 console.log('Actual engine typed domain payload parity PASS');
}else writeChangedArtifact(target,next);
